// <auto-generated>
//     Regenerated by docs/tools/envelope_check.py. DO NOT EDIT BY HAND.
//
//     These are the REFERENCE Best-of-N figures, integrated at 20000 nodes. The mod ships its
//     own 1024-node integrator (PawnVarianceSettings.CalculateBestOfNScoreCore) because
//     custom profiles need a live figure that no precomputed table can cover -- so there are
//     genuinely two implementations of the same integral, and they must agree.
//
//     The in-game debug action "Varied Pawns > Verify Best-of-N against envelope_check.py"
//     diffs the live integrator against this file. That is what makes the divergence
//     DETECTABLE rather than a comment someone has to remember to read. It is the exact bug
//     class that shipped once already: a Best-of-25 score compared against an N=1 baseline,
//     ~36pp wrong, with Desperate and Scavenger flipped positive.
//
//     The Gen* constants below snapshot what Constants.cs held at generation time. The debug
//     action compares them against the live values, so "changed a constant, forgot to re-run
//     the tool" is caught too -- a stale table cannot pass by looking self-consistent.
// </auto-generated>

namespace PawnVarianceMod
{
    public static class EnvelopeFigures
    {
        public const string Tool = "docs/tools/envelope_check.py";
        public const int ReferenceNodes = 20000;

        // Constants.cs values these figures were generated from. Mismatch against the live
        // Constants means this file is stale -- re-run the tool, do not adjust these.
        public const float GenCompositeSkillWeight = 0.8f;
        public const float GenCompositePassionWeight = 1.5f;
        public const float GenMaxPassionPips = 18f;
        public const float GenAssumedVanillaSkillBaseline = 5f;
        public const float GenAssumedMaxSkillLevel = 20f;
        public const float GenBetaConcentrationK = 8f;
        public const float GenQualityClampEpsilon = 0.001f;
        public const float GenMajorPassionCost = 1.5f;
        public const float GenMinorPassionCost = 1f;
        public const float GenPassionLearnRateNone = 0.35f;
        public const float GenPassionLearnRateMinor = 1f;
        public const float GenPassionLearnRateMajor = 1.5f;
        public const float GenMagnitudeLerpLow = 0f;
        public const float GenMaxMagnitude = 6f;
        public const float GenPassionBudgetSpreadMin = 0f;
        public const float GenPassionBudgetSpreadMax = 4f;
        public const float GenPassionBudgetClampFactor = 4f;
        public const float GenVanillaMajorBias = 0.5f;
        public const float GenVanillaPassionBudget = 5f;

        public static readonly int[] Batches = { 1, 5, 25, 50 };

        // Index-aligned with Batches. Display names, matching VarianceProfiles' labels.
        public static readonly string[] Profiles =
        {
            "Faithful",
            "Distinct",
            "Wildcard",
            "Desperate",
            "Elite",
            "Sovereign",
            "Specialist",
            "Scavenger"
        };

        public static readonly float[][] Scores =
        {
            new[] { 0.241788f, 0.304097f, 0.345480f, 0.359540f },
            new[] { 0.220714f, 0.311727f, 0.378294f, 0.401538f },
            new[] { 0.235755f, 0.347024f, 0.427101f, 0.454972f },
            new[] { 0.188354f, 0.244513f, 0.284016f, 0.297796f },
            new[] { 0.295424f, 0.354067f, 0.393094f, 0.406474f },
            new[] { 0.305290f, 0.365143f, 0.404615f, 0.418091f },
            new[] { 0.264359f, 0.326129f, 0.367280f, 0.381307f },
            new[] { 0.207727f, 0.266139f, 0.306204f, 0.320024f }
        };
    }
}
