// <auto-generated>
//     Regenerated by docs/tools/envelope_check.py. DO NOT EDIT BY HAND.
//
//     These are the REFERENCE Best-of-N figures, integrated at 20000 nodes. The mod ships its
//     own 1024-node integrator (PawnVarianceSettings.CalculateBestOfNScoreCore) because
//     custom profiles need a live figure that no precomputed table can cover -- so there are
//     genuinely two implementations of the same integral, and they must agree.
//
//     The in-game debug action "Varied Pawns > Verify Best-of-N against envelope_check.py"
//     diffs the live integrator against this file. That is what makes the divergence
//     DETECTABLE rather than a comment someone has to remember to read. It is the exact bug
//     class that shipped once already: a Best-of-25 score compared against an N=1 baseline,
//     ~36pp wrong, with Desperate and Scavenger flipped positive.
//
//     The Gen* constants below snapshot what Constants.cs held at generation time. The debug
//     action compares them against the live values, so "changed a constant, forgot to re-run
//     the tool" is caught too -- a stale table cannot pass by looking self-consistent.
// </auto-generated>

namespace PawnVarianceMod
{
    public static class EnvelopeFigures
    {
        public const string Tool = "docs/tools/envelope_check.py";
        public const int ReferenceNodes = 20000;

        // Constants.cs values these figures were generated from. Mismatch against the live
        // Constants means this file is stale -- re-run the tool, do not adjust these.
        public const float GenCompositeSkillWeight = 0.8f;
        public const float GenCompositePassionWeight = 1.5f;
        public const float GenMaxPassionPips = 18f;
        public const float GenAssumedVanillaSkillBaseline = 5f;
        public const float GenAssumedMaxSkillLevel = 20f;
        public const float GenBetaConcentrationK = 8f;
        public const float GenQualityClampEpsilon = 0.001f;
        public const float GenMajorPassionCost = 1.5f;
        public const float GenMinorPassionCost = 1f;
        public const float GenPassionLearnRateNone = 0.35f;
        public const float GenPassionLearnRateMinor = 1f;
        public const float GenPassionLearnRateMajor = 1.5f;

        public static readonly int[] Batches = { 1, 5, 25, 50 };

        // Index-aligned with Batches. Display names, matching VarianceProfiles' labels.
        public static readonly string[] Profiles =
        {
            "Faithful",
            "Distinct",
            "Wildcard",
            "Desperate",
            "Elite",
            "Sovereign",
            "Specialist",
            "Scavenger"
        };

        public static readonly float[][] Scores =
        {
            new[] { 0.223062f, 0.269890f, 0.297777f, 0.305949f },
            new[] { 0.199511f, 0.271672f, 0.324396f, 0.341768f },
            new[] { 0.176731f, 0.272065f, 0.342416f, 0.364886f },
            new[] { 0.170399f, 0.210477f, 0.238118f, 0.246946f },
            new[] { 0.275898f, 0.316725f, 0.340193f, 0.346921f },
            new[] { 0.285513f, 0.327597f, 0.351198f, 0.357858f },
            new[] { 0.245073f, 0.290609f, 0.317729f, 0.325677f },
            new[] { 0.189217f, 0.231381f, 0.258574f, 0.266933f }
        };
    }
}
