// <auto-generated>
//     Regenerated by docs/tools/envelope_check.py. DO NOT EDIT BY HAND.
//
//     These are the REFERENCE Best-of-N figures, integrated at 20000 nodes. The mod ships its
//     own 1024-node integrator (PawnVarianceSettings.CalculateBestOfNScoreCore) because
//     custom profiles need a live figure that no precomputed table can cover -- so there are
//     genuinely two implementations of the same integral, and they must agree.
//
//     The in-game debug action "Varied Pawns > Verify Best-of-N against envelope_check.py"
//     diffs the live integrator against this file. That is what makes the divergence
//     DETECTABLE rather than a comment someone has to remember to read. It is the exact bug
//     class that shipped once already: a Best-of-25 score compared against an N=1 baseline,
//     ~36pp wrong, with Desperate and Scavenger flipped positive.
//
//     The Gen* constants below snapshot what Constants.cs held at generation time. The debug
//     action compares them against the live values, so "changed a constant, forgot to re-run
//     the tool" is caught too -- a stale table cannot pass by looking self-consistent.
// </auto-generated>

namespace PawnVarianceMod
{
    public static class EnvelopeFigures
    {
        public const string Tool = "docs/tools/envelope_check.py";
        public const int ReferenceNodes = 20000;

        // Constants.cs values these figures were generated from. Mismatch against the live
        // Constants means this file is stale -- re-run the tool, do not adjust these.
        public const float GenCompositeSkillWeight = 0.8f;
        public const float GenCompositePassionWeight = 1.5f;
        public const float GenMaxPassionPips = 18f;
        public const float GenAssumedVanillaSkillBaseline = 5f;
        public const float GenAssumedMaxSkillLevel = 20f;
        public const float GenBetaConcentrationK = 8f;
        public const float GenQualityClampEpsilon = 0.001f;
        public const float GenMajorPassionCost = 1.5f;
        public const float GenMinorPassionCost = 1f;
        public const float GenPassionLearnRateNone = 0.35f;
        public const float GenPassionLearnRateMinor = 1f;
        public const float GenPassionLearnRateMajor = 1.5f;

        public static readonly int[] Batches = { 1, 5, 25, 50 };

        // Index-aligned with Batches. Display names, matching VarianceProfiles' labels.
        public static readonly string[] Profiles =
        {
            "Faithful",
            "Distinct",
            "Wildcard",
            "Desperate",
            "Elite",
            "Sovereign",
            "Specialist",
            "Scavenger"
        };

        public static readonly float[][] Scores =
        {
            new[] { 0.257089f, 0.303922f, 0.331816f, 0.339991f },
            new[] { 0.234955f, 0.307122f, 0.359850f, 0.377224f },
            new[] { 0.245070f, 0.334536f, 0.396238f, 0.415941f },
            new[] { 0.203580f, 0.243664f, 0.271310f, 0.280140f },
            new[] { 0.310673f, 0.351507f, 0.374981f, 0.381713f },
            new[] { 0.320520f, 0.362610f, 0.386218f, 0.392883f },
            new[] { 0.279609f, 0.325150f, 0.352277f, 0.360228f },
            new[] { 0.222974f, 0.265143f, 0.292341f, 0.300702f }
        };
    }
}
